/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage.impl;

import edu.upb.lp.isc.dymeLanguage.Asignacion;
import edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage;
import edu.upb.lp.isc.dymeLanguage.Objeto;
import edu.upb.lp.isc.dymeLanguage.Valor;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Asignacion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.impl.AsignacionImpl#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.impl.AsignacionImpl#isTipoInferido <em>Tipo Inferido</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.impl.AsignacionImpl#getTipoClass <em>Tipo Class</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.impl.AsignacionImpl#getValorAsig <em>Valor Asig</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AsignacionImpl extends DeclaracionImpl implements Asignacion
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #isTipoInferido() <em>Tipo Inferido</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isTipoInferido()
   * @generated
   * @ordered
   */
  protected static final boolean TIPO_INFERIDO_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isTipoInferido() <em>Tipo Inferido</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isTipoInferido()
   * @generated
   * @ordered
   */
  protected boolean tipoInferido = TIPO_INFERIDO_EDEFAULT;

  /**
   * The cached value of the '{@link #getTipoClass() <em>Tipo Class</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoClass()
   * @generated
   * @ordered
   */
  protected Objeto tipoClass;

  /**
   * The cached value of the '{@link #getValorAsig() <em>Valor Asig</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValorAsig()
   * @generated
   * @ordered
   */
  protected Valor valorAsig;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AsignacionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DymeLanguagePackage.Literals.ASIGNACION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DymeLanguagePackage.ASIGNACION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isTipoInferido()
  {
    return tipoInferido;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoInferido(boolean newTipoInferido)
  {
    boolean oldTipoInferido = tipoInferido;
    tipoInferido = newTipoInferido;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DymeLanguagePackage.ASIGNACION__TIPO_INFERIDO, oldTipoInferido, tipoInferido));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Objeto getTipoClass()
  {
    return tipoClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTipoClass(Objeto newTipoClass, NotificationChain msgs)
  {
    Objeto oldTipoClass = tipoClass;
    tipoClass = newTipoClass;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DymeLanguagePackage.ASIGNACION__TIPO_CLASS, oldTipoClass, newTipoClass);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoClass(Objeto newTipoClass)
  {
    if (newTipoClass != tipoClass)
    {
      NotificationChain msgs = null;
      if (tipoClass != null)
        msgs = ((InternalEObject)tipoClass).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DymeLanguagePackage.ASIGNACION__TIPO_CLASS, null, msgs);
      if (newTipoClass != null)
        msgs = ((InternalEObject)newTipoClass).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DymeLanguagePackage.ASIGNACION__TIPO_CLASS, null, msgs);
      msgs = basicSetTipoClass(newTipoClass, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DymeLanguagePackage.ASIGNACION__TIPO_CLASS, newTipoClass, newTipoClass));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Valor getValorAsig()
  {
    return valorAsig;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValorAsig(Valor newValorAsig, NotificationChain msgs)
  {
    Valor oldValorAsig = valorAsig;
    valorAsig = newValorAsig;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DymeLanguagePackage.ASIGNACION__VALOR_ASIG, oldValorAsig, newValorAsig);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValorAsig(Valor newValorAsig)
  {
    if (newValorAsig != valorAsig)
    {
      NotificationChain msgs = null;
      if (valorAsig != null)
        msgs = ((InternalEObject)valorAsig).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DymeLanguagePackage.ASIGNACION__VALOR_ASIG, null, msgs);
      if (newValorAsig != null)
        msgs = ((InternalEObject)newValorAsig).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DymeLanguagePackage.ASIGNACION__VALOR_ASIG, null, msgs);
      msgs = basicSetValorAsig(newValorAsig, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DymeLanguagePackage.ASIGNACION__VALOR_ASIG, newValorAsig, newValorAsig));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DymeLanguagePackage.ASIGNACION__TIPO_CLASS:
        return basicSetTipoClass(null, msgs);
      case DymeLanguagePackage.ASIGNACION__VALOR_ASIG:
        return basicSetValorAsig(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DymeLanguagePackage.ASIGNACION__NAME:
        return getName();
      case DymeLanguagePackage.ASIGNACION__TIPO_INFERIDO:
        return isTipoInferido();
      case DymeLanguagePackage.ASIGNACION__TIPO_CLASS:
        return getTipoClass();
      case DymeLanguagePackage.ASIGNACION__VALOR_ASIG:
        return getValorAsig();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DymeLanguagePackage.ASIGNACION__NAME:
        setName((String)newValue);
        return;
      case DymeLanguagePackage.ASIGNACION__TIPO_INFERIDO:
        setTipoInferido((Boolean)newValue);
        return;
      case DymeLanguagePackage.ASIGNACION__TIPO_CLASS:
        setTipoClass((Objeto)newValue);
        return;
      case DymeLanguagePackage.ASIGNACION__VALOR_ASIG:
        setValorAsig((Valor)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DymeLanguagePackage.ASIGNACION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DymeLanguagePackage.ASIGNACION__TIPO_INFERIDO:
        setTipoInferido(TIPO_INFERIDO_EDEFAULT);
        return;
      case DymeLanguagePackage.ASIGNACION__TIPO_CLASS:
        setTipoClass((Objeto)null);
        return;
      case DymeLanguagePackage.ASIGNACION__VALOR_ASIG:
        setValorAsig((Valor)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DymeLanguagePackage.ASIGNACION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DymeLanguagePackage.ASIGNACION__TIPO_INFERIDO:
        return tipoInferido != TIPO_INFERIDO_EDEFAULT;
      case DymeLanguagePackage.ASIGNACION__TIPO_CLASS:
        return tipoClass != null;
      case DymeLanguagePackage.ASIGNACION__VALOR_ASIG:
        return valorAsig != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", tipoInferido: ");
    result.append(tipoInferido);
    result.append(')');
    return result.toString();
  }

} //AsignacionImpl
