/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage.impl;

import edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage;
import edu.upb.lp.isc.dymeLanguage.Objeto;
import edu.upb.lp.isc.dymeLanguage.Primitivo;
import edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tipo Funcion Orden Superior</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.impl.TipoFuncionOrdenSuperiorImpl#getOrdenSuperiorTipo <em>Orden Superior Tipo</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.impl.TipoFuncionOrdenSuperiorImpl#getParamFunc <em>Param Func</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.impl.TipoFuncionOrdenSuperiorImpl#isReturnTipoFunc <em>Return Tipo Func</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.impl.TipoFuncionOrdenSuperiorImpl#getReturnFunc <em>Return Func</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TipoFuncionOrdenSuperiorImpl extends MinimalEObjectImpl.Container implements TipoFuncionOrdenSuperior
{
  /**
   * The default value of the '{@link #getOrdenSuperiorTipo() <em>Orden Superior Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOrdenSuperiorTipo()
   * @generated
   * @ordered
   */
  protected static final String ORDEN_SUPERIOR_TIPO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOrdenSuperiorTipo() <em>Orden Superior Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOrdenSuperiorTipo()
   * @generated
   * @ordered
   */
  protected String ordenSuperiorTipo = ORDEN_SUPERIOR_TIPO_EDEFAULT;

  /**
   * The cached value of the '{@link #getParamFunc() <em>Param Func</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParamFunc()
   * @generated
   * @ordered
   */
  protected EList<Objeto> paramFunc;

  /**
   * The default value of the '{@link #isReturnTipoFunc() <em>Return Tipo Func</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isReturnTipoFunc()
   * @generated
   * @ordered
   */
  protected static final boolean RETURN_TIPO_FUNC_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isReturnTipoFunc() <em>Return Tipo Func</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isReturnTipoFunc()
   * @generated
   * @ordered
   */
  protected boolean returnTipoFunc = RETURN_TIPO_FUNC_EDEFAULT;

  /**
   * The cached value of the '{@link #getReturnFunc() <em>Return Func</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReturnFunc()
   * @generated
   * @ordered
   */
  protected Primitivo returnFunc;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TipoFuncionOrdenSuperiorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DymeLanguagePackage.Literals.TIPO_FUNCION_ORDEN_SUPERIOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOrdenSuperiorTipo()
  {
    return ordenSuperiorTipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOrdenSuperiorTipo(String newOrdenSuperiorTipo)
  {
    String oldOrdenSuperiorTipo = ordenSuperiorTipo;
    ordenSuperiorTipo = newOrdenSuperiorTipo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__ORDEN_SUPERIOR_TIPO, oldOrdenSuperiorTipo, ordenSuperiorTipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Objeto> getParamFunc()
  {
    if (paramFunc == null)
    {
      paramFunc = new EObjectContainmentEList<Objeto>(Objeto.class, this, DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__PARAM_FUNC);
    }
    return paramFunc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isReturnTipoFunc()
  {
    return returnTipoFunc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReturnTipoFunc(boolean newReturnTipoFunc)
  {
    boolean oldReturnTipoFunc = returnTipoFunc;
    returnTipoFunc = newReturnTipoFunc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_TIPO_FUNC, oldReturnTipoFunc, returnTipoFunc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Primitivo getReturnFunc()
  {
    return returnFunc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReturnFunc(Primitivo newReturnFunc, NotificationChain msgs)
  {
    Primitivo oldReturnFunc = returnFunc;
    returnFunc = newReturnFunc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC, oldReturnFunc, newReturnFunc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReturnFunc(Primitivo newReturnFunc)
  {
    if (newReturnFunc != returnFunc)
    {
      NotificationChain msgs = null;
      if (returnFunc != null)
        msgs = ((InternalEObject)returnFunc).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC, null, msgs);
      if (newReturnFunc != null)
        msgs = ((InternalEObject)newReturnFunc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC, null, msgs);
      msgs = basicSetReturnFunc(newReturnFunc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC, newReturnFunc, newReturnFunc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__PARAM_FUNC:
        return ((InternalEList<?>)getParamFunc()).basicRemove(otherEnd, msgs);
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC:
        return basicSetReturnFunc(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__ORDEN_SUPERIOR_TIPO:
        return getOrdenSuperiorTipo();
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__PARAM_FUNC:
        return getParamFunc();
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_TIPO_FUNC:
        return isReturnTipoFunc();
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC:
        return getReturnFunc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__ORDEN_SUPERIOR_TIPO:
        setOrdenSuperiorTipo((String)newValue);
        return;
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__PARAM_FUNC:
        getParamFunc().clear();
        getParamFunc().addAll((Collection<? extends Objeto>)newValue);
        return;
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_TIPO_FUNC:
        setReturnTipoFunc((Boolean)newValue);
        return;
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC:
        setReturnFunc((Primitivo)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__ORDEN_SUPERIOR_TIPO:
        setOrdenSuperiorTipo(ORDEN_SUPERIOR_TIPO_EDEFAULT);
        return;
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__PARAM_FUNC:
        getParamFunc().clear();
        return;
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_TIPO_FUNC:
        setReturnTipoFunc(RETURN_TIPO_FUNC_EDEFAULT);
        return;
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC:
        setReturnFunc((Primitivo)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__ORDEN_SUPERIOR_TIPO:
        return ORDEN_SUPERIOR_TIPO_EDEFAULT == null ? ordenSuperiorTipo != null : !ORDEN_SUPERIOR_TIPO_EDEFAULT.equals(ordenSuperiorTipo);
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__PARAM_FUNC:
        return paramFunc != null && !paramFunc.isEmpty();
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_TIPO_FUNC:
        return returnTipoFunc != RETURN_TIPO_FUNC_EDEFAULT;
      case DymeLanguagePackage.TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC:
        return returnFunc != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ordenSuperiorTipo: ");
    result.append(ordenSuperiorTipo);
    result.append(", returnTipoFunc: ");
    result.append(returnTipoFunc);
    result.append(')');
    return result.toString();
  }

} //TipoFuncionOrdenSuperiorImpl
