/*
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DymeLanguageUiModule extends AbstractDymeLanguageUiModule {

	public DymeLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
