/*
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.upb.lp.isc.DymeLanguageRuntimeModule;
import edu.upb.lp.isc.DymeLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DymeLanguageIdeSetup extends DymeLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DymeLanguageRuntimeModule(), new DymeLanguageIdeModule()));
	}
	
}
