/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaracion</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getDeclaracion()
 * @model
 * @generated
 */
public interface Declaracion extends Instrucciones
{
} // Declaracion
