/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.upb.lp.isc.dymeLanguage.DymeLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface DymeLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dymeLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upb.edu/lp/isc/DymeLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dymeLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DymeLanguagePackage eINSTANCE = edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ProgramaImpl <em>Programa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.ProgramaImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getPrograma()
   * @generated
   */
  int PROGRAMA = 0;

  /**
   * The feature id for the '<em><b>Func</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__FUNC = 0;

  /**
   * The number of structural features of the '<em>Programa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ExpresionImpl <em>Expresion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.ExpresionImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getExpresion()
   * @generated
   */
  int EXPRESION = 10;

  /**
   * The number of structural features of the '<em>Expresion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.EstrellaFugazMeteoroImpl <em>Estrella Fugaz Meteoro</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.EstrellaFugazMeteoroImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getEstrellaFugazMeteoro()
   * @generated
   */
  int ESTRELLA_FUGAZ_METEORO = 1;

  /**
   * The feature id for the '<em><b>Expr Log Condicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTRELLA_FUGAZ_METEORO__EXPR_LOG_CONDICION = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Estrella Fugaz Res</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTRELLA_FUGAZ_METEORO__ESTRELLA_FUGAZ_RES = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Meteoro Res</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTRELLA_FUGAZ_METEORO__METEORO_RES = EXPRESION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Estrella Fugaz Meteoro</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTRELLA_FUGAZ_METEORO_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.FuncionImpl <em>Funcion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.FuncionImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getFuncion()
   * @generated
   */
  int FUNCION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__NAME = 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__PARAM = 1;

  /**
   * The feature id for the '<em><b>Instr</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__INSTR = 2;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__EXPR = 3;

  /**
   * The feature id for the '<em><b>Return Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__RETURN_TIPO = 4;

  /**
   * The feature id for the '<em><b>Tipo Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__TIPO_CLASS = 5;

  /**
   * The number of structural features of the '<em>Funcion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.LlamadoFuncImpl <em>Llamado Func</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.LlamadoFuncImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getLlamadoFunc()
   * @generated
   */
  int LLAMADO_FUNC = 3;

  /**
   * The feature id for the '<em><b>Funcion</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAMADO_FUNC__FUNCION = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAMADO_FUNC__ARGS = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Llamado Func</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAMADO_FUNC_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ParamImpl <em>Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.ParamImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getParam()
   * @generated
   */
  int PARAM = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__TIPO_CLASS = 1;

  /**
   * The number of structural features of the '<em>Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.InstruccionImpl <em>Instruccion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.InstruccionImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getInstruccion()
   * @generated
   */
  int INSTRUCCION = 5;

  /**
   * The number of structural features of the '<em>Instruccion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.AsignacionImpl <em>Asignacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.AsignacionImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getAsignacion()
   * @generated
   */
  int ASIGNACION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION__NAME = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tipo Inferido</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION__TIPO_INFERIDO = INSTRUCCION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Tipo Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION__TIPO_CLASS = INSTRUCCION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Valor Asig</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION__VALOR_ASIG = INSTRUCCION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Asignacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.TipoFuncionOrdenSuperiorImpl <em>Tipo Funcion Orden Superior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.TipoFuncionOrdenSuperiorImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getTipoFuncionOrdenSuperior()
   * @generated
   */
  int TIPO_FUNCION_ORDEN_SUPERIOR = 8;

  /**
   * The feature id for the '<em><b>Orden Superior Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_FUNCION_ORDEN_SUPERIOR__ORDEN_SUPERIOR_TIPO = 0;

  /**
   * The feature id for the '<em><b>Param Func</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_FUNCION_ORDEN_SUPERIOR__PARAM_FUNC = 1;

  /**
   * The feature id for the '<em><b>Return Tipo Func</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_TIPO_FUNC = 2;

  /**
   * The feature id for the '<em><b>Return Func</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC = 3;

  /**
   * The number of structural features of the '<em>Tipo Funcion Orden Superior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_FUNCION_ORDEN_SUPERIOR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.TipoImpl <em>Tipo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.TipoImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getTipo()
   * @generated
   */
  int TIPO = 7;

  /**
   * The feature id for the '<em><b>Orden Superior Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO__ORDEN_SUPERIOR_TIPO = TIPO_FUNCION_ORDEN_SUPERIOR__ORDEN_SUPERIOR_TIPO;

  /**
   * The feature id for the '<em><b>Param Func</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO__PARAM_FUNC = TIPO_FUNCION_ORDEN_SUPERIOR__PARAM_FUNC;

  /**
   * The feature id for the '<em><b>Return Tipo Func</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO__RETURN_TIPO_FUNC = TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_TIPO_FUNC;

  /**
   * The feature id for the '<em><b>Return Func</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO__RETURN_FUNC = TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO__TIPO = TIPO_FUNCION_ORDEN_SUPERIOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Tipo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_FEATURE_COUNT = TIPO_FUNCION_ORDEN_SUPERIOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ConstanteImpl <em>Constante</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.ConstanteImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getConstante()
   * @generated
   */
  int CONSTANTE = 9;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE__NOMBRE = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Constante</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ExprConcatenacionImpl <em>Expr Concatenacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.ExprConcatenacionImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getExprConcatenacion()
   * @generated
   */
  int EXPR_CONCATENACION = 11;

  /**
   * The feature id for the '<em><b>Operador Con</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONCATENACION__OPERADOR_CON = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr Con</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONCATENACION__EXPR_CON = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONCATENACION__X = EXPRESION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Expr Concatenacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONCATENACION_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ExprAritmeticaImpl <em>Expr Aritmetica</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.ExprAritmeticaImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getExprAritmetica()
   * @generated
   */
  int EXPR_ARITMETICA = 12;

  /**
   * The feature id for the '<em><b>Operador Ar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_ARITMETICA__OPERADOR_AR = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr Ar</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_ARITMETICA__EXPR_AR = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expr Aritmetica</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_ARITMETICA_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ExprLogicaImpl <em>Expr Logica</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.ExprLogicaImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getExprLogica()
   * @generated
   */
  int EXPR_LOGICA = 13;

  /**
   * The feature id for the '<em><b>Operador Log</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LOGICA__OPERADOR_LOG = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr Log</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LOGICA__EXPR_LOG = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expr Logica</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LOGICA_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ExprComparacionImpl <em>Expr Comparacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.ExprComparacionImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getExprComparacion()
   * @generated
   */
  int EXPR_COMPARACION = 14;

  /**
   * The feature id for the '<em><b>Operador Log</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_COMPARACION__OPERADOR_LOG = EXPR_LOGICA__OPERADOR_LOG;

  /**
   * The feature id for the '<em><b>Expr Log</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_COMPARACION__EXPR_LOG = EXPR_LOGICA__EXPR_LOG;

  /**
   * The feature id for the '<em><b>Operador Comp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_COMPARACION__OPERADOR_COMP = EXPR_LOGICA_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr Com Izq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_COMPARACION__EXPR_COM_IZQ = EXPR_LOGICA_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Expr Com Der</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_COMPARACION__EXPR_COM_DER = EXPR_LOGICA_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Expr Comparacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_COMPARACION_FEATURE_COUNT = EXPR_LOGICA_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.PlanetaImpl <em>Planeta</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.PlanetaImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getPlaneta()
   * @generated
   */
  int PLANETA = 15;

  /**
   * The feature id for the '<em><b>Operador Ar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANETA__OPERADOR_AR = EXPR_ARITMETICA__OPERADOR_AR;

  /**
   * The feature id for the '<em><b>Expr Ar</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANETA__EXPR_AR = EXPR_ARITMETICA__EXPR_AR;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANETA__X = EXPR_ARITMETICA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Planeta</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANETA_FEATURE_COUNT = EXPR_ARITMETICA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ConstelacionImpl <em>Constelacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.ConstelacionImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getConstelacion()
   * @generated
   */
  int CONSTELACION = 16;

  /**
   * The feature id for the '<em><b>Operador Con</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTELACION__OPERADOR_CON = EXPR_CONCATENACION__OPERADOR_CON;

  /**
   * The feature id for the '<em><b>Expr Con</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTELACION__EXPR_CON = EXPR_CONCATENACION__EXPR_CON;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTELACION__X = EXPR_CONCATENACION__X;

  /**
   * The number of structural features of the '<em>Constelacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTELACION_FEATURE_COUNT = EXPR_CONCATENACION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.EstrellaImpl <em>Estrella</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.EstrellaImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getEstrella()
   * @generated
   */
  int ESTRELLA = 17;

  /**
   * The feature id for the '<em><b>Operador Con</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTRELLA__OPERADOR_CON = EXPR_CONCATENACION__OPERADOR_CON;

  /**
   * The feature id for the '<em><b>Expr Con</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTRELLA__EXPR_CON = EXPR_CONCATENACION__EXPR_CON;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTRELLA__X = EXPR_CONCATENACION__X;

  /**
   * The number of structural features of the '<em>Estrella</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTRELLA_FEATURE_COUNT = EXPR_CONCATENACION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.PolvoEstelarImpl <em>Polvo Estelar</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.PolvoEstelarImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getPolvoEstelar()
   * @generated
   */
  int POLVO_ESTELAR = 18;

  /**
   * The feature id for the '<em><b>Operador Ar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLVO_ESTELAR__OPERADOR_AR = EXPR_ARITMETICA__OPERADOR_AR;

  /**
   * The feature id for the '<em><b>Expr Ar</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLVO_ESTELAR__EXPR_AR = EXPR_ARITMETICA__EXPR_AR;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLVO_ESTELAR__X = EXPR_ARITMETICA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Polvo Estelar</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLVO_ESTELAR_FEATURE_COUNT = EXPR_ARITMETICA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.dymeLanguage.impl.LunaImpl <em>Luna</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.dymeLanguage.impl.LunaImpl
   * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getLuna()
   * @generated
   */
  int LUNA = 19;

  /**
   * The feature id for the '<em><b>Operador Log</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNA__OPERADOR_LOG = EXPR_LOGICA__OPERADOR_LOG;

  /**
   * The feature id for the '<em><b>Expr Log</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNA__EXPR_LOG = EXPR_LOGICA__EXPR_LOG;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNA__X = EXPR_LOGICA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Luna</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNA_FEATURE_COUNT = EXPR_LOGICA_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Programa <em>Programa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programa</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Programa
   * @generated
   */
  EClass getPrograma();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.dymeLanguage.Programa#getFunc <em>Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Func</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Programa#getFunc()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Func();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro <em>Estrella Fugaz Meteoro</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Estrella Fugaz Meteoro</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro
   * @generated
   */
  EClass getEstrellaFugazMeteoro();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getExprLogCondicion <em>Expr Log Condicion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr Log Condicion</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getExprLogCondicion()
   * @see #getEstrellaFugazMeteoro()
   * @generated
   */
  EReference getEstrellaFugazMeteoro_ExprLogCondicion();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getEstrellaFugazRes <em>Estrella Fugaz Res</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Estrella Fugaz Res</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getEstrellaFugazRes()
   * @see #getEstrellaFugazMeteoro()
   * @generated
   */
  EReference getEstrellaFugazMeteoro_EstrellaFugazRes();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getMeteoroRes <em>Meteoro Res</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Meteoro Res</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getMeteoroRes()
   * @see #getEstrellaFugazMeteoro()
   * @generated
   */
  EReference getEstrellaFugazMeteoro_MeteoroRes();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Funcion <em>Funcion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Funcion</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Funcion
   * @generated
   */
  EClass getFuncion();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.Funcion#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Funcion#getName()
   * @see #getFuncion()
   * @generated
   */
  EAttribute getFuncion_Name();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.dymeLanguage.Funcion#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Funcion#getParam()
   * @see #getFuncion()
   * @generated
   */
  EReference getFuncion_Param();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.dymeLanguage.Funcion#getInstr <em>Instr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instr</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Funcion#getInstr()
   * @see #getFuncion()
   * @generated
   */
  EReference getFuncion_Instr();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.Funcion#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Funcion#getExpr()
   * @see #getFuncion()
   * @generated
   */
  EReference getFuncion_Expr();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.Funcion#isReturnTipo <em>Return Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Return Tipo</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Funcion#isReturnTipo()
   * @see #getFuncion()
   * @generated
   */
  EAttribute getFuncion_ReturnTipo();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.Funcion#getTipoClass <em>Tipo Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo Class</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Funcion#getTipoClass()
   * @see #getFuncion()
   * @generated
   */
  EReference getFuncion_TipoClass();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.LlamadoFunc <em>Llamado Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Llamado Func</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.LlamadoFunc
   * @generated
   */
  EClass getLlamadoFunc();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.dymeLanguage.LlamadoFunc#getFuncion <em>Funcion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Funcion</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.LlamadoFunc#getFuncion()
   * @see #getLlamadoFunc()
   * @generated
   */
  EReference getLlamadoFunc_Funcion();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.dymeLanguage.LlamadoFunc#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.LlamadoFunc#getArgs()
   * @see #getLlamadoFunc()
   * @generated
   */
  EReference getLlamadoFunc_Args();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Param
   * @generated
   */
  EClass getParam();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.Param#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Param#getName()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_Name();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.Param#getTipoClass <em>Tipo Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo Class</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Param#getTipoClass()
   * @see #getParam()
   * @generated
   */
  EReference getParam_TipoClass();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Instruccion <em>Instruccion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruccion</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Instruccion
   * @generated
   */
  EClass getInstruccion();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Asignacion <em>Asignacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asignacion</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Asignacion
   * @generated
   */
  EClass getAsignacion();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.Asignacion#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Asignacion#getName()
   * @see #getAsignacion()
   * @generated
   */
  EAttribute getAsignacion_Name();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.Asignacion#isTipoInferido <em>Tipo Inferido</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Inferido</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Asignacion#isTipoInferido()
   * @see #getAsignacion()
   * @generated
   */
  EAttribute getAsignacion_TipoInferido();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.Asignacion#getTipoClass <em>Tipo Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo Class</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Asignacion#getTipoClass()
   * @see #getAsignacion()
   * @generated
   */
  EReference getAsignacion_TipoClass();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.Asignacion#getValorAsig <em>Valor Asig</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Valor Asig</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Asignacion#getValorAsig()
   * @see #getAsignacion()
   * @generated
   */
  EReference getAsignacion_ValorAsig();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Tipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tipo</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Tipo
   * @generated
   */
  EClass getTipo();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.Tipo#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Tipo#getTipo()
   * @see #getTipo()
   * @generated
   */
  EAttribute getTipo_Tipo();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior <em>Tipo Funcion Orden Superior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tipo Funcion Orden Superior</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior
   * @generated
   */
  EClass getTipoFuncionOrdenSuperior();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getOrdenSuperiorTipo <em>Orden Superior Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Orden Superior Tipo</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getOrdenSuperiorTipo()
   * @see #getTipoFuncionOrdenSuperior()
   * @generated
   */
  EAttribute getTipoFuncionOrdenSuperior_OrdenSuperiorTipo();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getParamFunc <em>Param Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param Func</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getParamFunc()
   * @see #getTipoFuncionOrdenSuperior()
   * @generated
   */
  EReference getTipoFuncionOrdenSuperior_ParamFunc();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#isReturnTipoFunc <em>Return Tipo Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Return Tipo Func</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#isReturnTipoFunc()
   * @see #getTipoFuncionOrdenSuperior()
   * @generated
   */
  EAttribute getTipoFuncionOrdenSuperior_ReturnTipoFunc();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getReturnFunc <em>Return Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return Func</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getReturnFunc()
   * @see #getTipoFuncionOrdenSuperior()
   * @generated
   */
  EReference getTipoFuncionOrdenSuperior_ReturnFunc();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Constante <em>Constante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constante</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Constante
   * @generated
   */
  EClass getConstante();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.dymeLanguage.Constante#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Nombre</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Constante#getNombre()
   * @see #getConstante()
   * @generated
   */
  EReference getConstante_Nombre();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Expresion <em>Expresion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expresion</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Expresion
   * @generated
   */
  EClass getExpresion();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.ExprConcatenacion <em>Expr Concatenacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Concatenacion</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprConcatenacion
   * @generated
   */
  EClass getExprConcatenacion();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.ExprConcatenacion#getOperadorCon <em>Operador Con</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador Con</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprConcatenacion#getOperadorCon()
   * @see #getExprConcatenacion()
   * @generated
   */
  EAttribute getExprConcatenacion_OperadorCon();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.dymeLanguage.ExprConcatenacion#getExprCon <em>Expr Con</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expr Con</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprConcatenacion#getExprCon()
   * @see #getExprConcatenacion()
   * @generated
   */
  EReference getExprConcatenacion_ExprCon();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.ExprConcatenacion#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprConcatenacion#getX()
   * @see #getExprConcatenacion()
   * @generated
   */
  EAttribute getExprConcatenacion_X();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.ExprAritmetica <em>Expr Aritmetica</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Aritmetica</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprAritmetica
   * @generated
   */
  EClass getExprAritmetica();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.ExprAritmetica#getOperadorAr <em>Operador Ar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador Ar</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprAritmetica#getOperadorAr()
   * @see #getExprAritmetica()
   * @generated
   */
  EAttribute getExprAritmetica_OperadorAr();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.dymeLanguage.ExprAritmetica#getExprAr <em>Expr Ar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expr Ar</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprAritmetica#getExprAr()
   * @see #getExprAritmetica()
   * @generated
   */
  EReference getExprAritmetica_ExprAr();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.ExprLogica <em>Expr Logica</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Logica</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprLogica
   * @generated
   */
  EClass getExprLogica();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.ExprLogica#getOperadorLog <em>Operador Log</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador Log</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprLogica#getOperadorLog()
   * @see #getExprLogica()
   * @generated
   */
  EAttribute getExprLogica_OperadorLog();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.dymeLanguage.ExprLogica#getExprLog <em>Expr Log</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expr Log</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprLogica#getExprLog()
   * @see #getExprLogica()
   * @generated
   */
  EReference getExprLogica_ExprLog();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.ExprComparacion <em>Expr Comparacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Comparacion</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprComparacion
   * @generated
   */
  EClass getExprComparacion();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.ExprComparacion#getOperadorComp <em>Operador Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador Comp</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprComparacion#getOperadorComp()
   * @see #getExprComparacion()
   * @generated
   */
  EAttribute getExprComparacion_OperadorComp();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.ExprComparacion#getExprComIzq <em>Expr Com Izq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr Com Izq</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprComparacion#getExprComIzq()
   * @see #getExprComparacion()
   * @generated
   */
  EReference getExprComparacion_ExprComIzq();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.dymeLanguage.ExprComparacion#getExprComDer <em>Expr Com Der</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr Com Der</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.ExprComparacion#getExprComDer()
   * @see #getExprComparacion()
   * @generated
   */
  EReference getExprComparacion_ExprComDer();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Planeta <em>Planeta</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Planeta</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Planeta
   * @generated
   */
  EClass getPlaneta();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.Planeta#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Planeta#getX()
   * @see #getPlaneta()
   * @generated
   */
  EAttribute getPlaneta_X();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Constelacion <em>Constelacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constelacion</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Constelacion
   * @generated
   */
  EClass getConstelacion();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Estrella <em>Estrella</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Estrella</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Estrella
   * @generated
   */
  EClass getEstrella();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.PolvoEstelar <em>Polvo Estelar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Polvo Estelar</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.PolvoEstelar
   * @generated
   */
  EClass getPolvoEstelar();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.PolvoEstelar#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.PolvoEstelar#getX()
   * @see #getPolvoEstelar()
   * @generated
   */
  EAttribute getPolvoEstelar_X();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.dymeLanguage.Luna <em>Luna</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Luna</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Luna
   * @generated
   */
  EClass getLuna();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.dymeLanguage.Luna#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see edu.upb.lp.isc.dymeLanguage.Luna#getX()
   * @see #getLuna()
   * @generated
   */
  EAttribute getLuna_X();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DymeLanguageFactory getDymeLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ProgramaImpl <em>Programa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.ProgramaImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getPrograma()
     * @generated
     */
    EClass PROGRAMA = eINSTANCE.getPrograma();

    /**
     * The meta object literal for the '<em><b>Func</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__FUNC = eINSTANCE.getPrograma_Func();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.EstrellaFugazMeteoroImpl <em>Estrella Fugaz Meteoro</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.EstrellaFugazMeteoroImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getEstrellaFugazMeteoro()
     * @generated
     */
    EClass ESTRELLA_FUGAZ_METEORO = eINSTANCE.getEstrellaFugazMeteoro();

    /**
     * The meta object literal for the '<em><b>Expr Log Condicion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESTRELLA_FUGAZ_METEORO__EXPR_LOG_CONDICION = eINSTANCE.getEstrellaFugazMeteoro_ExprLogCondicion();

    /**
     * The meta object literal for the '<em><b>Estrella Fugaz Res</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESTRELLA_FUGAZ_METEORO__ESTRELLA_FUGAZ_RES = eINSTANCE.getEstrellaFugazMeteoro_EstrellaFugazRes();

    /**
     * The meta object literal for the '<em><b>Meteoro Res</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESTRELLA_FUGAZ_METEORO__METEORO_RES = eINSTANCE.getEstrellaFugazMeteoro_MeteoroRes();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.FuncionImpl <em>Funcion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.FuncionImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getFuncion()
     * @generated
     */
    EClass FUNCION = eINSTANCE.getFuncion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCION__NAME = eINSTANCE.getFuncion_Name();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION__PARAM = eINSTANCE.getFuncion_Param();

    /**
     * The meta object literal for the '<em><b>Instr</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION__INSTR = eINSTANCE.getFuncion_Instr();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION__EXPR = eINSTANCE.getFuncion_Expr();

    /**
     * The meta object literal for the '<em><b>Return Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCION__RETURN_TIPO = eINSTANCE.getFuncion_ReturnTipo();

    /**
     * The meta object literal for the '<em><b>Tipo Class</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION__TIPO_CLASS = eINSTANCE.getFuncion_TipoClass();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.LlamadoFuncImpl <em>Llamado Func</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.LlamadoFuncImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getLlamadoFunc()
     * @generated
     */
    EClass LLAMADO_FUNC = eINSTANCE.getLlamadoFunc();

    /**
     * The meta object literal for the '<em><b>Funcion</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LLAMADO_FUNC__FUNCION = eINSTANCE.getLlamadoFunc_Funcion();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LLAMADO_FUNC__ARGS = eINSTANCE.getLlamadoFunc_Args();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ParamImpl <em>Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.ParamImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getParam()
     * @generated
     */
    EClass PARAM = eINSTANCE.getParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__NAME = eINSTANCE.getParam_Name();

    /**
     * The meta object literal for the '<em><b>Tipo Class</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAM__TIPO_CLASS = eINSTANCE.getParam_TipoClass();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.InstruccionImpl <em>Instruccion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.InstruccionImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getInstruccion()
     * @generated
     */
    EClass INSTRUCCION = eINSTANCE.getInstruccion();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.AsignacionImpl <em>Asignacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.AsignacionImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getAsignacion()
     * @generated
     */
    EClass ASIGNACION = eINSTANCE.getAsignacion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASIGNACION__NAME = eINSTANCE.getAsignacion_Name();

    /**
     * The meta object literal for the '<em><b>Tipo Inferido</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASIGNACION__TIPO_INFERIDO = eINSTANCE.getAsignacion_TipoInferido();

    /**
     * The meta object literal for the '<em><b>Tipo Class</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASIGNACION__TIPO_CLASS = eINSTANCE.getAsignacion_TipoClass();

    /**
     * The meta object literal for the '<em><b>Valor Asig</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASIGNACION__VALOR_ASIG = eINSTANCE.getAsignacion_ValorAsig();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.TipoImpl <em>Tipo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.TipoImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getTipo()
     * @generated
     */
    EClass TIPO = eINSTANCE.getTipo();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPO__TIPO = eINSTANCE.getTipo_Tipo();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.TipoFuncionOrdenSuperiorImpl <em>Tipo Funcion Orden Superior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.TipoFuncionOrdenSuperiorImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getTipoFuncionOrdenSuperior()
     * @generated
     */
    EClass TIPO_FUNCION_ORDEN_SUPERIOR = eINSTANCE.getTipoFuncionOrdenSuperior();

    /**
     * The meta object literal for the '<em><b>Orden Superior Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPO_FUNCION_ORDEN_SUPERIOR__ORDEN_SUPERIOR_TIPO = eINSTANCE.getTipoFuncionOrdenSuperior_OrdenSuperiorTipo();

    /**
     * The meta object literal for the '<em><b>Param Func</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIPO_FUNCION_ORDEN_SUPERIOR__PARAM_FUNC = eINSTANCE.getTipoFuncionOrdenSuperior_ParamFunc();

    /**
     * The meta object literal for the '<em><b>Return Tipo Func</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_TIPO_FUNC = eINSTANCE.getTipoFuncionOrdenSuperior_ReturnTipoFunc();

    /**
     * The meta object literal for the '<em><b>Return Func</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIPO_FUNCION_ORDEN_SUPERIOR__RETURN_FUNC = eINSTANCE.getTipoFuncionOrdenSuperior_ReturnFunc();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ConstanteImpl <em>Constante</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.ConstanteImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getConstante()
     * @generated
     */
    EClass CONSTANTE = eINSTANCE.getConstante();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTANTE__NOMBRE = eINSTANCE.getConstante_Nombre();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ExpresionImpl <em>Expresion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.ExpresionImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getExpresion()
     * @generated
     */
    EClass EXPRESION = eINSTANCE.getExpresion();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ExprConcatenacionImpl <em>Expr Concatenacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.ExprConcatenacionImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getExprConcatenacion()
     * @generated
     */
    EClass EXPR_CONCATENACION = eINSTANCE.getExprConcatenacion();

    /**
     * The meta object literal for the '<em><b>Operador Con</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_CONCATENACION__OPERADOR_CON = eINSTANCE.getExprConcatenacion_OperadorCon();

    /**
     * The meta object literal for the '<em><b>Expr Con</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_CONCATENACION__EXPR_CON = eINSTANCE.getExprConcatenacion_ExprCon();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_CONCATENACION__X = eINSTANCE.getExprConcatenacion_X();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ExprAritmeticaImpl <em>Expr Aritmetica</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.ExprAritmeticaImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getExprAritmetica()
     * @generated
     */
    EClass EXPR_ARITMETICA = eINSTANCE.getExprAritmetica();

    /**
     * The meta object literal for the '<em><b>Operador Ar</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_ARITMETICA__OPERADOR_AR = eINSTANCE.getExprAritmetica_OperadorAr();

    /**
     * The meta object literal for the '<em><b>Expr Ar</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_ARITMETICA__EXPR_AR = eINSTANCE.getExprAritmetica_ExprAr();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ExprLogicaImpl <em>Expr Logica</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.ExprLogicaImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getExprLogica()
     * @generated
     */
    EClass EXPR_LOGICA = eINSTANCE.getExprLogica();

    /**
     * The meta object literal for the '<em><b>Operador Log</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_LOGICA__OPERADOR_LOG = eINSTANCE.getExprLogica_OperadorLog();

    /**
     * The meta object literal for the '<em><b>Expr Log</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_LOGICA__EXPR_LOG = eINSTANCE.getExprLogica_ExprLog();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ExprComparacionImpl <em>Expr Comparacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.ExprComparacionImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getExprComparacion()
     * @generated
     */
    EClass EXPR_COMPARACION = eINSTANCE.getExprComparacion();

    /**
     * The meta object literal for the '<em><b>Operador Comp</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_COMPARACION__OPERADOR_COMP = eINSTANCE.getExprComparacion_OperadorComp();

    /**
     * The meta object literal for the '<em><b>Expr Com Izq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_COMPARACION__EXPR_COM_IZQ = eINSTANCE.getExprComparacion_ExprComIzq();

    /**
     * The meta object literal for the '<em><b>Expr Com Der</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_COMPARACION__EXPR_COM_DER = eINSTANCE.getExprComparacion_ExprComDer();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.PlanetaImpl <em>Planeta</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.PlanetaImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getPlaneta()
     * @generated
     */
    EClass PLANETA = eINSTANCE.getPlaneta();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLANETA__X = eINSTANCE.getPlaneta_X();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.ConstelacionImpl <em>Constelacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.ConstelacionImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getConstelacion()
     * @generated
     */
    EClass CONSTELACION = eINSTANCE.getConstelacion();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.EstrellaImpl <em>Estrella</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.EstrellaImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getEstrella()
     * @generated
     */
    EClass ESTRELLA = eINSTANCE.getEstrella();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.PolvoEstelarImpl <em>Polvo Estelar</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.PolvoEstelarImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getPolvoEstelar()
     * @generated
     */
    EClass POLVO_ESTELAR = eINSTANCE.getPolvoEstelar();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POLVO_ESTELAR__X = eINSTANCE.getPolvoEstelar_X();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.dymeLanguage.impl.LunaImpl <em>Luna</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.dymeLanguage.impl.LunaImpl
     * @see edu.upb.lp.isc.dymeLanguage.impl.DymeLanguagePackageImpl#getLuna()
     * @generated
     */
    EClass LUNA = eINSTANCE.getLuna();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LUNA__X = eINSTANCE.getLuna_X();

  }

} //DymeLanguagePackage
