/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Estrella Fugaz Meteoro</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getExprLogCondicion <em>Expr Log Condicion</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getEstrellaFugazRes <em>Estrella Fugaz Res</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getMeteoroRes <em>Meteoro Res</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getEstrellaFugazMeteoro()
 * @model
 * @generated
 */
public interface EstrellaFugazMeteoro extends Expresion
{
  /**
   * Returns the value of the '<em><b>Expr Log Condicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Log Condicion</em>' containment reference.
   * @see #setExprLogCondicion(Expresion)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getEstrellaFugazMeteoro_ExprLogCondicion()
   * @model containment="true"
   * @generated
   */
  Expresion getExprLogCondicion();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getExprLogCondicion <em>Expr Log Condicion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr Log Condicion</em>' containment reference.
   * @see #getExprLogCondicion()
   * @generated
   */
  void setExprLogCondicion(Expresion value);

  /**
   * Returns the value of the '<em><b>Estrella Fugaz Res</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Estrella Fugaz Res</em>' containment reference.
   * @see #setEstrellaFugazRes(Expresion)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getEstrellaFugazMeteoro_EstrellaFugazRes()
   * @model containment="true"
   * @generated
   */
  Expresion getEstrellaFugazRes();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getEstrellaFugazRes <em>Estrella Fugaz Res</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Estrella Fugaz Res</em>' containment reference.
   * @see #getEstrellaFugazRes()
   * @generated
   */
  void setEstrellaFugazRes(Expresion value);

  /**
   * Returns the value of the '<em><b>Meteoro Res</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Meteoro Res</em>' containment reference.
   * @see #setMeteoroRes(Expresion)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getEstrellaFugazMeteoro_MeteoroRes()
   * @model containment="true"
   * @generated
   */
  Expresion getMeteoroRes();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.EstrellaFugazMeteoro#getMeteoroRes <em>Meteoro Res</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Meteoro Res</em>' containment reference.
   * @see #getMeteoroRes()
   * @generated
   */
  void setMeteoroRes(Expresion value);

} // EstrellaFugazMeteoro
