/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Map Operaciones</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.ExprMapOperaciones#getOperadorAdd <em>Operador Add</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.ExprMapOperaciones#getMapConst <em>Map Const</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.ExprMapOperaciones#getKey <em>Key</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getExprMapOperaciones()
 * @model
 * @generated
 */
public interface ExprMapOperaciones extends Valor
{
  /**
   * Returns the value of the '<em><b>Operador Add</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operador Add</em>' attribute.
   * @see #setOperadorAdd(String)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getExprMapOperaciones_OperadorAdd()
   * @model
   * @generated
   */
  String getOperadorAdd();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.ExprMapOperaciones#getOperadorAdd <em>Operador Add</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operador Add</em>' attribute.
   * @see #getOperadorAdd()
   * @generated
   */
  void setOperadorAdd(String value);

  /**
   * Returns the value of the '<em><b>Map Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map Const</em>' containment reference.
   * @see #setMapConst(Constante)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getExprMapOperaciones_MapConst()
   * @model containment="true"
   * @generated
   */
  Constante getMapConst();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.ExprMapOperaciones#getMapConst <em>Map Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Map Const</em>' containment reference.
   * @see #getMapConst()
   * @generated
   */
  void setMapConst(Constante value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.dymeLanguage.Expresion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' containment reference list.
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getExprMapOperaciones_Key()
   * @model containment="true"
   * @generated
   */
  EList<Expresion> getKey();

} // ExprMapOperaciones
