/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Aritmetica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.ExprAritmetica#getOperadorAr <em>Operador Ar</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.ExprAritmetica#getExprAr <em>Expr Ar</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getExprAritmetica()
 * @model
 * @generated
 */
public interface ExprAritmetica extends Expresion
{
  /**
   * Returns the value of the '<em><b>Operador Ar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operador Ar</em>' attribute.
   * @see #setOperadorAr(String)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getExprAritmetica_OperadorAr()
   * @model
   * @generated
   */
  String getOperadorAr();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.ExprAritmetica#getOperadorAr <em>Operador Ar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operador Ar</em>' attribute.
   * @see #getOperadorAr()
   * @generated
   */
  void setOperadorAr(String value);

  /**
   * Returns the value of the '<em><b>Expr Ar</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.dymeLanguage.Expresion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Ar</em>' containment reference list.
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getExprAritmetica_ExprAr()
   * @model containment="true"
   * @generated
   */
  EList<Expresion> getExprAr();

} // ExprAritmetica
