/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.ExprSimple#getX <em>X</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.ExprSimple#getP <em>P</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getExprSimple()
 * @model
 * @generated
 */
public interface ExprSimple extends Expresion
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(String)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getExprSimple_X()
   * @model
   * @generated
   */
  String getX();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.ExprSimple#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(String value);

  /**
   * Returns the value of the '<em><b>P</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P</em>' attribute.
   * @see #setP(String)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getExprSimple_P()
   * @model
   * @generated
   */
  String getP();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.ExprSimple#getP <em>P</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P</em>' attribute.
   * @see #getP()
   * @generated
   */
  void setP(String value);

} // ExprSimple
