/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Remove</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getMapRemove()
 * @model
 * @generated
 */
public interface MapRemove extends ExprMapOperaciones
{
} // MapRemove
