/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Polvo Estelar</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.PolvoEstelar#getX <em>X</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getPolvoEstelar()
 * @model
 * @generated
 */
public interface PolvoEstelar extends ExprAritmetica
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(double)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getPolvoEstelar_X()
   * @model
   * @generated
   */
  double getX();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.PolvoEstelar#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(double value);

} // PolvoEstelar
