/**
 * generated by Xtext 2.26.0
 */
package edu.upb.lp.isc.dymeLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tipo Funcion Orden Superior</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getOrdenSuperiorTipo <em>Orden Superior Tipo</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getParamFunc <em>Param Func</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#isReturnTipoFunc <em>Return Tipo Func</em>}</li>
 *   <li>{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getReturnFunc <em>Return Func</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getTipoFuncionOrdenSuperior()
 * @model
 * @generated
 */
public interface TipoFuncionOrdenSuperior extends EObject
{
  /**
   * Returns the value of the '<em><b>Orden Superior Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Orden Superior Tipo</em>' attribute.
   * @see #setOrdenSuperiorTipo(String)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getTipoFuncionOrdenSuperior_OrdenSuperiorTipo()
   * @model
   * @generated
   */
  String getOrdenSuperiorTipo();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getOrdenSuperiorTipo <em>Orden Superior Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Orden Superior Tipo</em>' attribute.
   * @see #getOrdenSuperiorTipo()
   * @generated
   */
  void setOrdenSuperiorTipo(String value);

  /**
   * Returns the value of the '<em><b>Param Func</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Func</em>' containment reference list.
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getTipoFuncionOrdenSuperior_ParamFunc()
   * @model containment="true"
   * @generated
   */
  EList<TipoFuncionOrdenSuperior> getParamFunc();

  /**
   * Returns the value of the '<em><b>Return Tipo Func</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Tipo Func</em>' attribute.
   * @see #setReturnTipoFunc(boolean)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getTipoFuncionOrdenSuperior_ReturnTipoFunc()
   * @model
   * @generated
   */
  boolean isReturnTipoFunc();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#isReturnTipoFunc <em>Return Tipo Func</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Tipo Func</em>' attribute.
   * @see #isReturnTipoFunc()
   * @generated
   */
  void setReturnTipoFunc(boolean value);

  /**
   * Returns the value of the '<em><b>Return Func</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Func</em>' containment reference.
   * @see #setReturnFunc(TipoFuncionOrdenSuperior)
   * @see edu.upb.lp.isc.dymeLanguage.DymeLanguagePackage#getTipoFuncionOrdenSuperior_ReturnFunc()
   * @model containment="true"
   * @generated
   */
  TipoFuncionOrdenSuperior getReturnFunc();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.dymeLanguage.TipoFuncionOrdenSuperior#getReturnFunc <em>Return Func</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Func</em>' containment reference.
   * @see #getReturnFunc()
   * @generated
   */
  void setReturnFunc(TipoFuncionOrdenSuperior value);

} // TipoFuncionOrdenSuperior
